title: Yuanchao Su's Homepage
page-top-title: Yuanchao Su 
top-section-bg-text: Remote Sensing Image Processing and Analysis 
home-subtitle: Yuanchao Su &ensp;|&ensp; 蘇遠超 &ensp;|&ensp; 苏远超
copyright-text: '&copy; Yuanchao Su 2025-2026. All Rights Reserved.'
